# 1. URL de conexi�n (cambia 'nombre_tu_db' por el nombre real de tu base de datos)
spring.datasource.url=jdbc:mysql://localhost:3306/reporteExcel2026?serverTimezone=UTC&useSSL=false&createDatabaseIfNotExist=true

# 2. Credenciales de acceso
spring.datasource.username=root
spring.datasource.password=Lucca2026

# 3. Driver de MySQL (Spring Boot suele detectarlo, pero es mejor definirlo)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. Configuraci�n de Hibernate / JPA
# update: Crea las tablas si no existen o las actualiza sin borrar datos.
# create-drop: Borra y crea todo cada vez que inicias (ideal para pruebas).
spring.jpa.hibernate.ddl-auto=update

# 5. Mostrar las consultas SQL en la consola (�til para debugear)
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Aseg�rate de que el nivel de log no est� en DEBUG para SQL
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=ERROR

# 6. Dialecto para que Hibernate hable "MySQL moderno"
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

excel.header = [Seccion, Ramo, Fecha, Numero, Cliente, Riesgo, Status, Motivo, AdjudicadoA, Moneda, MontoAdjudicado, MontoCotizado, RiesgoCosto1, RiesgoCosto2, AdjudicadoCosto1, AdjudicadoCosto2, AdjudicadoCosto3]

#La posicion del array indica el renglon de cada riesgo
excel.renglon.riesgo = [RC COMPRENSIVA, RC ASCENSORES, RC CALDERAS, RC GUARDA/DEPOSITO, RC CARTELES, INCENDIO, TECNICO EQ. ELECTRONICOS, APC, ROBO Y RIESGOS SIMILARES, VALORES EN TRANSITO, VALORES EN CAJA, TR INSTRUMENTOS MUSICALES, TR OBRAS DE ARTE, DRONES, INTEGRAL, AERONAVEACION, CAUCION, TRO, TRANSPORTE, SEPELIO, VIDA, SALUD, FRANQUICIAS]
