# 1. URL de conexion (cambia 'nombre_tu_db' por el nombre real de tu base de datos)
spring.datasource.url=jdbc:mysql://localhost:3306/reporteExcel2026?serverTimezone=UTC&useSSL=false&createDatabaseIfNotExist=true

server.servlet.context-path=/api/v1
server.port=8080

# 2. Credenciales de acceso
spring.datasource.username=root
spring.datasource.password=Lucca2026

# 3. Driver de MySQL (Spring Boot suele detectarlo, pero es mejor definirlo)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. Configuracion de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update

# 5. Mostrar las consultas SQL en la consola
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=ERROR

# 6. Dialecto para que Hibernate hable MySQL moderno
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 7. Limite de tamano para carga de archivos Excel
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

excel.header = [Seccion, Ramo, Fecha, Numero, Cliente, Riesgo, Status, Estado Motivo, Motivo, AdjudicadoA, Moneda, MontoAdjudicado, MontoCotizado, CotizadoCosto1, CotizadoCosto2, AdjudicadoCosto1, AdjudicadoCosto2, AdjudicadoCosto3]

#La posicion del array indica el renglon de cada riesgo
excel.renglon.riesgo = [RC COMPRENSIVA, RC ASCENSORES, RC CALDERAS, RC GUARDA/DEPOSITO, RC CARTELES, INCENDIO, TECNICO EQ. ELECTRONICOS, APC, ROBO Y RIESGOS SIMILARES, VALORES EN TRANSITO, VALORES EN CAJA, TR INSTRUMENTOS MUSICALES, TR OBRAS DE ARTE, DRONES, INTEGRAL, AERONAVEACION, CAUCION, TRO, TRANSPORTE, SEPELIO, VIDA, SALUD, FRANQUICIAS]
